name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none' # Para private project

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^4.2.0
  firebase_auth: ^6.1.1
  cloud_firestore: ^6.1.0

  # State management
  provider: ^6.1.5+1

  # Formatting & fonts
  intl: ^0.20.2
  google_fonts: ^6.3.2

  # Splash screen
  flutter_native_splash: 2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: 0.14.4 # <-- Added for automatic launcher icons

flutter:

  uses-material-design: true

  assets:
    - assets/images/app_logo.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_logo.png
  android: true
  ios: true
  web: true
  android_12:
    color: "#FFFFFF"
    image: assets/images/app_logo.png

# Launcher icon configuration
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_logo.png"